/*
* Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License").
* You may not use this file except in compliance with the License.
* A copy of the License is located at
*
*  http://aws.amazon.com/apache2.0
*
* or in the "license" file accompanying this file. This file is distributed
* on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
* express or implied. See the License for the specific language governing
* permissions and limitations under the License.
*/

// ignore_for_file: public_member_api_docs

enum Cuisine {
  AINU,
  ALBANIAN,
  ARGENTINE,
  ANDHRA,
  AMERICAN,
  ANGLO_INDIAN,
  ARAB,
  ARMENIAN,
  ASSYRIAN,
  AWADHI,
  AZERBAIJANI,
  BALOCHI,
  BASHKIR,
  BELARUSIAN,
  BANGLADESHI,
  BENGALI,
  BERBER,
  BRAZILIAN,
  BRITISH,
  BUDDHIST,
  BULGARIAN,
  CAJUN,
  CANTONESE,
  CARIBBEAN,
  CHECHEN,
  CHINESE,
  CIRCASSIAN,
  CRIMEAN_TATAR,
  CYPRIOT,
  CZECH,
  DANISH,
  EGYPTIAN,
  ENGLISH,
  ETHIOPIAN,
  ERITREAN,
  ESTONIAN,
  FRENCH,
  FILIPINO,
  GEORGIAN,
  GERMAN,
  GOAN,
  GOAN_CATHOLIC,
  GREEK,
  GUJARATI,
  HYDERABADI,
  INDIAN,
  INDIAN_CHINESE,
  INDIAN_SINGAPOREAN,
  INDONESIAN,
  INUIT,
  IRISH,
  ITALIAN_AMERICAN,
  ITALIAN,
  JAMAICAN,
  JAPANESE,
  JEWISH,
  KARNATAKA,
  KAZAKH,
  KERALITE,
  KOREAN,
  KURDISH,
  LAOTIAN,
  LEBANESE,
  LATVIAN,
  LITHUANIAN,
  LOUISIANA_CREOLE,
  MAHARASHTRIAN,
  MANGALOREAN,
  MALAY,
  MALAYSIAN_CHINESE,
  MALAYSIAN_INDIAN,
  MEDITERRANEAN,
  MENNONITE,
  MEXICAN,
  MORDOVIAN,
  MUGHAL,
  NATIVE_AMERICAN,
  NEPALESE,
  NEW_MEXICAN,
  ODIA,
  PARSI,
  PASHTUN,
  POLISH,
  PENNSYLVANIA_DUTCH,
  PAKISTANI,
  PERANAKAN,
  PERSIAN,
  PERUVIAN,
  PORTUGUESE,
  PUNJABI,
  RAJASTHANI,
  ROMANI,
  ROMANIAN,
  RUSSIAN,
  SAMI,
  SERBIAN,
  SINDHI,
  SLOVAK,
  SLOVENIAN,
  SOMALI,
  SOUTH_INDIAN,
  SOVIET,
  SPANISH,
  SRILANKAN,
  TAIWANESE,
  TATAR,
  TEXAN,
  THAI,
  TURKISH,
  TAMIL,
  UDUPI,
  UKRAINIAN,
  VIETNAMESE,
  YAMAL,
  ZAMBIAN,
  ZANZIBARI
}
